version: '2'
services:
  web:
    build: .
    volumes:
      - ./html:/var/www/html
    ports:
      - 80
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: db
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    ports:
      - 3306
    volumes:
      - ./data:/var/lib/mysql
